from fastapi import FastAPI
from pydantic import BaseModel
from services.trip_service import(calculate_daily_budget, get_trip_category, get_transportation_recommendation, get_recommended_place)
from models.trip import Trip
from database import SessionLocal, init_db

class TripRequest(BaseModel):
    destination:    str
    days:           int
    budget:         float
    travel_style:   str

app = FastAPI()

# create tables on startup
init_db()

#  GET endpoint at the root path
@app.get('/')
def home():
    return{
        'message' : 'Welcome to Kelana AI'
    }

# GET health
@app.get('/health')
def health():
    return{
        'status' : 'OK'
    }

@app.get('/trip-categories')
def trip_category():
    return ['Backpacker', 'Standard', 'Luxury']

@app.get('/api/v1/recommendations')
def recommendations():
    return ['Tokyo Tower', 'Mount Fuji', 'Shibuya']

@app.get('/api/v1/transportations')
def transportations():
    return ['Bus', 'Train', 'Flight']

# POST endpoint - receives JSON, return JSON
@app.post('/api/v1/trips')
def create_trip(request: TripRequest):
    daily_budget = calculate_daily_budget(
        request.budget, request.days
    )
    category = get_trip_category(
        request.budget
    )
    recommendation_transport = get_transportation_recommendation(category)
    recommendation_place = get_recommended_place(request.destination)
    
    # create trip ORM
    trip = Trip(
        destination = request.destination,
        days        = request.days,
        budget      = request.budget,
        category    = category,
        daily_budget= daily_budget,
    )

    # save to PostgresSQL
    db  = SessionLocal()
    db.add(trip)
    db.commit()
    db.refresh(trip)  #get the autogenerated id
    db.close()
    return trip

    @app.get('/api/v1/trips/{trip_id}')
    def get_trip(trip_id: int):
        db = SessionLocal()
        trip = db.query(Trip).filter(Trip.id == trip_id).first()
        db.close()
        # handling not found
        if trip is None:
            raise HTTPException(status_code=404, detail=f'Trip with id{trip_id} not found')
        return trip